include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    directives_ordering: false # Waste of time
    use_key_in_widget_constructors: false
    depend_on_referenced_packages: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    cascade_invocations: false
    unnecessary_lambdas: false
    sort_constructors_first: false
    prefer_single_quotes: false
    omit_local_variable_types: false
    avoid_positional_boolean_parameters: false
    flutter_style_todos: false
    avoid_redundant_argument_values: false
    use_raw_strings: false
    sort_pub_dependencies: false
    no_default_cases: false
    use_if_null_to_convert_nulls_to_bools: false
    prefer_asserts_with_message: false
    leading_newlines_in_multiline_strings: false
