name: country_code_picker
description: A flutter package for showing a country code selector. In addition it gives the possibility to select a list of favorites countries, as well as to search using a simple searchbox  
version: 3.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.13.9

dependencies:
  flutter:
    sdk: flutter

flutter:
  assets:
    - flags/
    - packages/country_code_picker/src/i18n/en.json
    - packages/country_code_picker/src/i18n/zh.json
    
dev_dependencies:
  very_good_analysis: 5.1.0
